     Red = '#FF6A7B'
  Maroon = '#FF7DAA'
    Pink = '#FF9ED0'
 Rosewat = '#FFBAE2'
Flamingo = '#FAA296'
   Peach = '#FF9856'
  Yellow = '#E9AD5B'
   Green = '#90D05A'
    Teal = '#41DDCA'
Sapphire = '#62E4FF'
    Sky  = '#05D1EC'
    Blue = '#6EA3FE'
Lavender = '#8995FF'
   Mauve = '#C198FD'
    Text = '#BECAF9'
Subtext1 = '#A7B1D9'
Subtext0 = '#99A4CC'
Overlay2 = '#919ABA'
Overlay1 = '#8087A2'
Overlay0 = '#6E738D'
Surface2 = '#5B6078'
Surface1 = '#494D64'
Surface0 = '#363A4F'
    Base = '#24273A'
  Mantle = '#1E2030'
   Crust = '#181926'

